apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-client
  name: test-client
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test-client
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-client
    spec:
      containers:
      - name: go-test-app
      # START ARGS OMIT
        args:
        - /secure-client
        - /tls/tls.pem
        - /tls/tls-key.pem
        - /tls/ca.pem
        - https://server:8443
      # END ARGS OMIT
        image: carsonoid/go-test-app
        imagePullPolicy: Never
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        # START MOUNT OMIT
        volumeMounts:
        - mountPath: /tls
          name: tls
          readOnly: true
        # END MOUNT OMIT
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      # START VOL OMIT
      volumes:
      - name: tls
        secret:
          defaultMode: 420
          secretName: client-tls
      # END VOL OMIT
