---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: server
spec:
  # Secret names are always required.
  secretName: server-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - UT Kubernetes
  commonName: server
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - localhost
    - server
  ipAddresses:
    - 127.0.0.1
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-server
  name: test-server
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-server
    spec:
      containers:
      - args:
        - /secure-server
        - /tls/tls.crt
        - /tls/tls.key
        - /tls/ca.crt
        image: carsonoid/go-test-app
        imagePullPolicy: IfNotPresent
        name: go-test-app
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tls
          name: tls
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: tls
        secret:
          defaultMode: 420
          secretName: server-tls
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-10-23T23:30:05Z"
  labels:
    app: test-server
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:internalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":8443,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl-expose
    operation: Update
    time: "2022-10-23T23:30:05Z"
  name: server
  namespace: default
  resourceVersion: "1298"
  uid: eeed34c7-7a7f-4a9f-81e0-fe0391c6151a
spec:
  clusterIP: 10.43.99.77
  clusterIPs:
  - 10.43.99.77
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8443
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-server
  name: server
spec:
  ports:
  - port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: test-server
  sessionAffinity: None
  type: ClusterIP
