---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-client
  template:
    metadata:
      labels:
        app: test-client
    spec:
      containers:
      # START FOCUS OMIT
      - image: carsonoid/go-test-app
        args:
        - /insecure-client
        - http://server.default.svc.cluster.local.:8080
      # END FOCUS OMIT
        # ...
        # END DEPLOYMENT OMIT
        imagePullPolicy: Never
        name: go-test-app
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
