---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-server
  template:
    metadata:
      labels:
        app: test-server
    spec:
      containers:
      # START FOCUS OMIT
      - image: carsonoid/go-test-app
        args:
        - /insecure-server
        # END FOCUS OMIT
        imagePullPolicy: Never
        name: go-test-app
      dnsPolicy: ClusterFirst
      # ...
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
# Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-server
  name: server
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: test-server
  sessionAffinity: None
  type: ClusterIP
