# START CERT OMIT
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: server
spec:
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  commonName: server
  dnsNames:
    - server
    - server.default.svc.cluster.local
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject: { organizations: ["UT Kubernetes"] }
  privateKey: { algorithm: RSA, encoding: PKCS1, size: 2048 }
  usages:
    - server auth
    - client auth
  # START SN OMIT
  secretName: server-tls
  # END SN OMIT
# END CERT OMIT
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-server
  name: test-server
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-server
    spec:
      containers:
      - name: go-test-app
        # START ARGS OMIT
        args:
        - /secure-server
        - /tls/tls.crt
        - /tls/tls.key
        - /tls/ca.crt
        # END ARGS OMIT
        image: carsonoid/go-test-app
        imagePullPolicy: Never
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tls
          name: tls
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      # START VOL OMIT
      volumes:
      - name: tls
        secret:
          defaultMode: 420
          secretName: server-tls
      # END VOL OMIT
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-server
  name: server
spec:
  ports:
  - port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: test-server
  sessionAffinity: None
  type: ClusterIP
