---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-client
  name: test-client
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test-client
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-client
    spec:
      containers:
      - args:
        - /client
        - /tls/tls.crt
        - /tls/tls.key
        - /tls/ca.crt
        - https://server.default.svc.cluster.local.:8443
        image: carsonoid/go-test-app
        imagePullPolicy: Never
        name: go-test-app
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tls
          name: tls
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: tls
          csi:
            readOnly: true
            driver: csi.cert-manager.io
            volumeAttributes:
              csi.cert-manager.io/issuer-kind: ClusterIssuer
              csi.cert-manager.io/issuer-name: vault-issuer

              # We don't expect other services to need to access this client pod, so we have no service dns names here
              csi.cert-manager.io/dns-names: ${POD_NAME},${POD_NAME}.${POD_NAMESPACE}.svc.cluster.local.

              # NOTE: could break as common name is limited to 64 chars and pod names can be larger
              # this is one of the reasons that common name has been deprecated since the year 2000
              # but it's included here to show that it *is* possible to set if needed for legacy software
              csi.cert-manager.io/common-name: ${POD_NAME}
